
title: Paul Notes
email: dr.paulnotes@gmail.com
description: A portfolio under construction
baseurl: "" # the subpath of your site, e.g. /blog

github_username:  abialbon

# Build settings
markdown: kramdown
